name: Linux Workflow
on: [push]

jobs:
  flask_integral_tests:
    name: integral tests run on linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: install flask requirements
        run: python -m pip install --upgrade pip setuptools && pip install -r requirements/dev.txt && pip install -e .
        shell: bash

      - name: install pip
        run: pip install pytest selenium flask-jwt-extended multiprocess flask-sqlalchemy
        shell: bash

      - name: run pytest
        run: pytest
        shell: bash
